apiVersion: v1
kind: Pod
metadata:
  labels:
    test: busybox-curl
  name: busybox-1
spec:
  containers:
  - name: liveness
    image: busybox
    args:
    - /bin/sh
    - -c
    - curl -k https://kubernetes.default/healthz; sleep 1200;